### ISSUE TITLE
Which version of crossbridge was this compiled with

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [normanzb/encoder-mp3#4]
Hi
I've tried using this with the latest version of CrossBridge, but it gets loads of compile errors.

Which version of crossbridge did you use to compile with ?

**Comment by normanzb** [comment]
Sorry mate this is something i've done 5 years ago, I can't remember which ver was it.
I don't even have the machine which used for compiling with me anymore... 

As adobe stopped supporting cross bridge 6 years ago, I reckon I was using the latest official version from adobe...

**Comment by rogerclarkmelbourne** [comment]
OK. No worries.  
Thanks for replying....
I did get the Crossbridge examples working, including Quake, which was pretty cool.

But it looks like its pointless trying to get this to compile, so I'll put my efforts into getting an AirNativeExtension fully working on all platforms
